name: Node.js (Windows) CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        working-directory: "./"
    strategy:
      matrix:
        # node-version: [14.x, 16.x, 18.x]
        node-version: [18.x]
        working-directory: [ "./" ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: cd
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: ${{ matrix.working-directory }}out/customterminal-win32-x64
